from pydantic import BaseModel, Field


class KafkaMessage(BaseModel):
    key: str = Field(description="Kafka message key")
    value: str = Field(description="JSON-строка значения Kafka-сообщения")


class TestStep(BaseModel):
    action: str = Field(description="Действие: REST-запрос, Kafka-сообщение или SQL-запрос для проверки БД")
    expected: str = Field(description="Ожидаемый результат: HTTP-код, значения полей, состояние в БД")


class TestCasePlanItem(BaseModel):
    """One test case plan item from call 1 (coverage plan)."""
    name: str = Field(description="Краткое название тест-кейса")
    category: str = Field(pattern="^(validation|positive|negative|edge_case)$")
    checks: str = Field(description="Что именно проверяем — конкретное поле, правило, ветка логики")
    priority: str = Field(pattern="^(high|medium|low)$")


class TestCasePlanResult(BaseModel):
    """Tool output schema for call 1 (plan phase)."""
    test_cases: list[TestCasePlanItem]


class SingleTestCaseResult(BaseModel):
    """One test case generated by Claude (call 2 — detail phase)."""
    name: str = Field(description="Краткое название тест-кейса на русском")
    category: str = Field(pattern="^(validation|positive|negative|edge_case)$", description="Категория тест-кейса из плана")
    preconditions: str = Field(description="Состояние данных перед тестом: записи в БД, настройки моков")
    steps: list[TestStep] = Field(description="Упорядоченные шаги тест-кейса")
    expected_result: str = Field(description="Итоговый ожидаемый результат после выполнения всех шагов")
    priority: str = Field(pattern="^(high|medium|low)$", description="Приоритет из плана: high | medium | low")
    curl_command: str | None = Field(default=None, description="curl-команда для REST-эндпоинта")
    kafka_message: KafkaMessage | None = Field(default=None, description="Kafka-сообщение (key + value)")
    sql_setup: str | None = Field(default=None, description="SQL-скрипт подготовки данных. DELETE затем INSERT. Без backticks")
    mock_config: str | None = Field(default=None, description="WireMock JSON mapping для мока зависимости")


class TestCaseGenerationResult(BaseModel):
    """Tool output schema for one category call."""
    test_cases: list[SingleTestCaseResult]


class TestCaseReviewRequest(BaseModel):
    """PATCH body for approving/editing/resetting a test case."""
    status: str = Field(pattern="^(pending|approved|edited)$")
    analyst_text: str | None = None
